### ISSUE TITLE
[Task] 테트리스 게임을 진행할 방 생성하기

### ISSUE THREAD

**Issue by jch422** [jch422/Tetris#4]
### ISSUE
Group: `client`, `server`
Type: `feature`

### TODO
- [ ] 고유한 ID를 생성해서 방 ID로 사용하기
- [ ] 방 인원수는 최대 2명으로 제한
- [ ] 방을 생성한 직후는 다른 플레이어가 오기 전까지 대기
- [ ] 다른 플레이어가 방에 들어와 2명이 되면 게임 진행 가능
- [ ] 방에 있는 사용자에게 대기, 진행 상태를 명확하게 표시

### Estimated time
`6h`
