### ISSUE TITLE
[Task] 테트리스 게임을 진행할 방 참가하기

### ISSUE THREAD

**Issue by jch422** [jch422/Tetris#5]
### ISSUE
Group: `client`, `server`
Type: `feature`

### TODO
- [ ] 방 ID를 주소창 혹은 입력창에 입력해서 참가 가능
- [ ] 상대 플레이어가 들어와 2人 되면 자동 시작
- [ ] 이미 2人 방에는 참가 불가능

### Estimated time
`3h`
