### ISSUE TITLE
[Task] 테트리스 로직 구현

### ISSUE THREAD

**Issue by jch422** [jch422/Tetris#6]
### ISSUE
Group: `client`, `server`
Type: `feature`

### TODO
- [ ] 테트리스 게임 로직을 구현
- [ ] 플레이어가 지우는 줄 수에 따라 점수 부여
- [ ] 자신과 상대의 게임 화면을 나란히 구현
- [ ] 실시간으로 서로의 화면, 점수 등이 공유 됨
- [ ] 한 명의 플레이어가 진행불가되는 시점에 게임도 종료

### Estimated time
`10h`
