### ISSUE TITLE
[Task] 아이템 획득 및 사용 기능 구현

### ISSUE THREAD

**Issue by jch422** [jch422/Tetris#9]
### ISSUE
Group: `client`
Type: `feature`

### TODO
- [ ] 블록 생성 시 일정한 확률로 cell에 아이템을 추가하기
- [ ] 해당 cell이 지워지게 되면 아이템 자동 사용
- [ ] 아이템 종류 및 효과 등은 추가적인 검토 필요...

### Estimated time
`6h`
